FROM node:20-alpine AS build

WORKDIR /app

COPY ./package*.json ./
RUN npm install -g @angular/cli@18.0.0
RUN npm install

COPY . .
# CMD ["ionic", "serve", "--host", "0.0.0.0", "--port", "8200", "--disable-host-check", "--poll", "2000"]
CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "8200", "--disable-host-check", "--poll", "2000"]
